[package]
name = "konnnyaku-common"
version = "0.1.0"
authors = ["shinyaigeek <philispaxil@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2.8"
